version: '3.6'
services:
    rabbit:
        container_name: dev_rabbit
        hostname: rabbit
        image: rabbitmq
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5672:5672"
            - "15672:15672"